### ISSUE TITLE
Access to samples

### ISSUE THREAD

**Issue by marcofarina84** [krishnap25/mauve-experiments#6]
Hi all!
Would it be possible to have access to the generated text samples?
Making them public would remove the burden of running continuations generation and would make reproducibility only tied to computing MAUVE and other metrics.

**Comment by jackjyzhang** [comment]
+1 on this issue. Providing the raw generated text string and/or the featurized text would be very helpful for reproducing the evaluation. Thanks a lot for your help!

**Comment by krishnap25** [comment]
Hi Marco and Jack,

Thank you for your interest in Mauve. Your requests make a lot of sense.

Due to pre-existing commitments, we can only act on this in early February.
At that point, we will look into what options are available to make the
generations public. In the meanwhile, if you have any suggestions, please
post them here.

Thank you.

Best,
Krishna

**Comment by marcofarina84** [comment]
Hi Krishna!
Do you have any update on this?
Thanks!

**Comment by krishnap25** [comment]
Hi @marcofarina84!

Sorry for the delay. I haven't found the time to figure out how to share them. We are trying to figure this out, please check back in 2 weeks.

**Comment by krishnap25** [comment]
Hi @marcofarina84 and @jackjyzhang, 

Sorry for the delay. We have uploaded the generations on Google Drive. Please see [here](https://github.com/krishnap25/mauve-experiments/blob/main/download_generations.md) for details.

Best,
Krishna
